### ISSUE TITLE
Uncaught ReferenceError: ws is not defined

### ISSUE THREAD

**Issue by JoshAtticus** [MeowerBots/meowerbot-web#1]
Uncaught ReferenceError: ws is not defined
    post https://meowerbots.github.io/meowerbot-web/main.js:66
    anonymous https://meowerbots.github.io/meowerbot-web/main.js line 8 > Function:7
    coding https://meowerbots.github.io/meowerbot-web/main.js:8
    startws https://meowerbots.github.io/meowerbot-web/main.js:9
    onclick https://meowerbots.github.io/meowerbot-web/:1

**Comment by JoshAtticus** [comment]
@Voxalice

**Comment by Voxalice** [comment]
I'm having a little trouble replicating this glitch -- did you try to manually post a message without typing your username and password?

**Comment by JoshAtticus** [comment]
> I'm having a little trouble replicating this glitch -- did you try to manually post a message without typing your username and password?

Oh yay I can actually run MDWalters125 after doing that!

**Comment by JoshAtticus** [comment]
Closed because no one else closed it
